name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.11.0" # Specifically using a stable v20 version

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9 # Matches the pnpm version you're using locally

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm next build